export const locations = [
	"Tokyo",
	"New York",
	"London",
	"Paris",
	"Beijing",
	"Mumbai",
	"Istanbul",
	"Rio de Janeiro",
	"Sydney",
	"Cairo",
	"Moscow",
	"Mexico City",
	"Toronto",
	"Dubai",
	"Seoul",
	"Lagos",
	"Berlin",
	"Buenos Aires",
	"Bangkok",
	"Cape Town",
	"Los Angeles",
	"Rome",
	"Shanghai",
	"Chicago",
	"Jakarta",
	"Madrid",
	"Karachi",
	"Lima",
	"Nairobi",
	"Hong Kong",
	"Munich",
	"Vancouver",
	"Amsterdam",
	"Singapore",
	"Johannesburg",
	"Osaka",
	"Kolkata",
	"Bogotá",
	"Vienna",
	"Stockholm",
	"Manila",
	"Houston",
	"Warsaw",
	"Lisbon",
	"Montreal",
	"Athens",
	"San Francisco",
	"Dublin",
	"Prague",
];

export const arbitraryString =
	"In the moonlit night, whispers of the wind reveal secrets of forgotten tales, as stars dance in the cosmic ballet, painting the sky with ethereal wonders.";

export const sampleImages = [
	"sample0.jpeg",
	"sample1.jpeg",
	"sample2.jpeg",
	"sample3.jpeg",
	"sample4.jpeg",
	"sample5.jpeg",
	"sample6.jpeg",
	"sample7.jpeg",
	"sample8.jpeg",
	"sample9.jpeg",
	"sample10.jpeg",
];
